package fr.insalyon.creatis.vip.cligatelab.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import fr.insalyon.creatis.vip.cligatelab.controller.SetApiKeyButtonControl;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static fr.insalyon.creatis.vip.cligatelab.controller.Main.EXECUTABLEFILE;

/**
 * Created by qifan on 2017/7/5.
 */
public class ApiKeyMenu {
    private JTextArea apiKeyArea;
    private JButton setButton;
    private JPanel JPanel1;

    public ApiKeyMenu() {
        String[] execCommand = new String[4];
        execCommand[0] = "java";
        execCommand[1] = "-jar";
        execCommand[2] = EXECUTABLEFILE;
        execCommand[3] = "getapikey";
        Process ps = null;
        try {
            ps = Runtime.getRuntime().exec(execCommand);


            try {
                ps.waitFor();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            InputStream is = ps.getErrorStream();
            byte b[] = new byte[is.available()];
            is.read(b, 0, b.length);


            InputStream is2 = ps.getInputStream();
            byte b2[] = new byte[is2.available()];
            is2.read(b2, 0, b2.length);
            String str = new String(b2);
            System.err.println(new String(b));
            Pattern p = Pattern.compile("\\s*|\t|\r|\n");
            Matcher m = p.matcher(str);
            str = m.replaceAll("");
            apiKeyArea.setText(str);
            setButton.addActionListener(new SetApiKeyButtonControl(this));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void setApiKeyArea(JTextArea apiKeyArea) {
        this.apiKeyArea = apiKeyArea;
    }

    public void setSetButton(JButton setButton) {
        this.setButton = setButton;
    }

    public JPanel getJPanel1() {
        return JPanel1;
    }

    public JTextArea getApiKeyArea() {

        return apiKeyArea;
    }

    public JButton getSetButton() {
        return setButton;
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPanel1 = new JPanel();
        JPanel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        apiKeyArea = new JTextArea();
        JPanel1.add(apiKeyArea, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        setButton = new JButton();
        setButton.setText("Set api key");
        JPanel1.add(setButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPanel1;
    }
}
