package fr.insalyon.creatis.vip.cligatelab.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

import static fr.insalyon.creatis.vip.cligatelab.controller.Main.INTERFACESCALE;
import static fr.insalyon.creatis.vip.cligatelab.controller.Main.SCREENHEIGHT;
import static fr.insalyon.creatis.vip.cligatelab.controller.Main.SCREENWIDTH;

/**
 * Created by qifan on 2017/7/12.
 */
public class DownloadMonitor {
    private JLabel InfoLabel;
    private JFrame actualFrame;
    private JLabel spinner;
    private JPanel panel;


    public DownloadMonitor() {
        actualFrame = new JFrame();
        actualFrame.setVisible(true);
        actualFrame.setBounds(0, 0, (int) (SCREENWIDTH * INTERFACESCALE * 0.2), (int) (SCREENHEIGHT * INTERFACESCALE * 0.2));
        actualFrame.setContentPane(panel);
        actualFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        spinner.setVisible(true);
    }

    public JLabel getInfoLabel() {


        return InfoLabel;
    }

    public JPanel getPanel() {
        return panel;
    }


    public JLabel getSpinner() {
        return spinner;
    }

    public JFrame getActualFrame() {
        return actualFrame;
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        spinner = new JLabel();
        spinner.setIcon(new ImageIcon(getClass().getResource("/Spinner.gif")));
        spinner.setText("downloading");
        panel.add(spinner, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        InfoLabel = new JLabel();
        InfoLabel.setText("");
        panel.add(InfoLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
